Drop the keyctl thing. use the environment variable

diff --git a/bwmenu b/bwmenu
--- a/bwmenu
+++ b/bwmenu
@@ -21,22 +21,18 @@ ROFI_OPTIONS=()
 
 ask_password() {
   mpw=$(rofi -dmenu -p "Master Password" -password -lines 0) || exit $?
-  echo "$mpw" | bw unlock 2>/dev/null | grep 'export' | sed -E 's/.*export BW_SESSION="(.*==)"$/\1/' || exit_error $? "Could not unlock vault"
+  if [[ ! -z $BW_SESSION ]]; then
+    echo $BW_SESSION
+  else
+    echo "$mpw" | bw unlock 2>/dev/null | grep 'export' | sed -E 's/.*export BW_SESSION="(.*==)"$/\1/' || exit_error $? "Could not unlock vault"
+  fi
 }
 
 get_session_key() {
-  if [ $AUTO_LOCK -eq 0 ]; then
-    keyctl purge user bw_session &>/dev/null
+  if [[ -z $BW_SESSION ]]; then
     BW_HASH=$(ask_password)
   else
-    if ! key_id=$(keyctl request user bw_session 2>/dev/null); then
-      session=$(ask_password)
-      [[ -z "$session" ]] && exit_error 1 "Could not unlock vault"
-      key_id=$(echo "$session" | keyctl padd user bw_session @u)
-    fi
-
-    keyctl timeout "$key_id" $AUTO_LOCK
-    BW_HASH=$(keyctl pipe "$key_id")
+    BW_HASH=$BW_SESSION
   fi
 }
 
